### ISSUE TITLE
fittizio

### ISSUE THREAD

**Issue by marte-git** [vanon-git/Compito1#1]
questo e' solo per vedere come funzionano le issue

risponda e la dichiaro chiusa

in effetti, a proposito di un'osservaizone che mette in fondo al readme, non e' necessario mettere il minisito in htdocs, perche' non ci sono funzionalita' (ad esempio chiamate di programma, codice php ...) che rendano necessaria l'intermediazione del web server.

A questo livello (HW1) basta aprire i file nella cartella.

Giusto per scrivere qualcosa ...

**Comment by vanon-git** [comment]
Va bene prof la ringrazio,
Pensavo fosse necessario inserire nelle specifiche dove andasse eseguito il
software
Cordiali saluti

Il gio 4 mag 2023, 13:19 marte-git ***@***.***> ha scritto:
